export const GHANA_BANKS = [
  "Absa Bank Ghana",
  "Access Bank Ghana",
  "Agricultural Development Bank (ADB)",
  "Bank of Africa",
  "CalBank",
  "Consolidated Bank Ghana (CBG)",
  "Ecobank Ghana",
  "FBNBank Ghana",
  "Fidelity Bank Ghana",
  "First Atlantic Bank",
  "First National Bank Ghana",
  "GCB Bank",
  "Guaranty Trust Bank (GTBank)",
  "National Investment Bank (NIB)",
  "OmniBSIC Bank",
  "Prudential Bank",
  "Republic Bank Ghana",
  "Société Générale Ghana",
  "Stanbic Bank Ghana",
  "Standard Chartered Bank Ghana",
  "United Bank for Africa (UBA)",
  "Universal Merchant Bank (UMB)",
  "Zenith Bank Ghana",
  "Other / Rural Bank"
];
